version: '3.8'

services:
  # PostgreSQL Service
  postgres:
    image: postgres:16         # airchie konkretuli versia radgan iyos compatible aplikaciastan ertad, roca daaupgraddeba 'latest' tag-i anu versia, sheildzleba agar wavides shen aplikaciastan eg konkretuli versia
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}                       # eseni secure unda iyos ise ro me ver vxedavde.
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  # Node.js Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: postgres
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_PORT: 5432
    expose:
      - "8080"
    depends_on:
      - postgres
    networks:
      - app-network

  # NGINX Service for Proxying
  nginx:
    image: nginx:1.27.1             # igive akac gasasworebelia
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge

